### PR TITLE
Add TTL support

### PR DESCRIPTION
**Pull request by russel5**
Share unlimited internet for free

### CODE REVIEW

**Comment by derfelot** [comment]
Can you tell me, what is the point to change the TTL exactly?

Also, please keep in line with the formatting. E.g. "config: [commit title]" and change it for all three devices.

**Comment by russel5** [comment]
Do you don't know for what need change TTL?
omg, how it's difficult.
nvm

**Comment by derfelot** [comment]
Are yoy serious? Yes,I know what changing a TTL does yes, but not how it would be useful to us .That's all I asked. Besides, it can cause some serious network issues, there's a reason why it is"EXTREMELY DANGEROUS"

**Comment by russel5** [comment]
I need throw out my wifi router as fast as i can...like it's make issues and dangerous

**Pull request closed without merging**
