### PR TITLE
Merge 4.4.188 into kernel.lnx.4.4.r40-rel

### PR DESCRIPTION
**Pull request by sjllls**
Linux 4.4.188 from mainline.

### CODE REVIEW

**Comment by derfelot** [comment]
Thanks. But personally, I'd prefer to not squash all commits into one. That way we can more easily track the changes and revert problematic ones individually in case of issues.

Also, the r40 branch follows a different caf tag than ours (can't look it up right now, but I think 7.2.r2 as compared to our 7.4.r1). So there _might_ be slight differences.

So I think it would be better to manually merge the Linux tag into our tree.

**Comment by sjllls** [comment]
> Thanks. But personally, I'd prefer to not squash all commits into one. That way we can more easily track the changes and revert problematic ones individually in case of issues.
> 
> Also, the r40 branch follows a different caf tag than ours (can't look it up right now, but I think 7.2.r2 as compared to our 7.4.r1). So there _might_ be slight differences.
> 
> So I think it would be better to manually merge the Linux tag into our tree.

Ok, Already modified this PR.

**Comment by derfelot** [comment]
Thanks that's better.

But what I meant is to fetch the 4.4.188 directly from kernel.org and merge this manually yourself. As it is now, all missing commits from android_linux_stable r40 branch are also added and we are not following that branch (we are following r35, but there are no updates anymore for it from Nathan's side).

Sorry for being so pedantic ;)

**Comment by sjllls** [comment]
> Thanks that's better.
> 
> But what I meant is to fetch the 4.4.188 directly from kernel.org and merge this manually yourself. As it is now, all missing commits from android_linux_stable r40 branch are also added and we are not following that branch (we are following r35, but there are no updates anymore for it from Nathan's side).
> 
> Sorry for being so pedantic ;)

Never mind,You are very careful. :+1:

**Comment by sjllls** [comment]
Modified, merge from kernel.org.

**Comment by derfelot** [comment]
perfect, thanks :)

**Pull request merged**
