### PR TITLE
Moved maple config to the right place

### PR DESCRIPTION
**Pull request by Umeaboy**

### CODE REVIEW

**Comment by C457** [comment]
Is this based of the AOSP defconfig? This tree is based on Sony kernel from their opensource archives. For instance some things should be broken the stock sony release uses CONFIG_SOMC_CHARGER_EXTENSION instead of CONFIG_QPNP_SMBFG_NEWGEN_EXTENSION there are possibly more renamed configs

**Comment by CurveOS** [comment]
I honestly think I got it from AICP-Sony which in turn got it from sonyxperiadev which in turn got it from AOSP.

**Comment by cryptomilk** [comment]
You're requesting merges for untested stuff?

**Comment by cryptomilk** [comment]
I've added a working maple config

**Pull request merged**
