### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by derfelot**
- Merge CAF tag LA.UM.6.2.r1-10900-sdm660.0
- Update qcacld-3.0 to LA.UM.6.2.r1-10900-sdm660.0
- Update to WireGuard 0.0.20180910 snapshot
- Update yoshino defconfig files for LA.UM.6.2.r1-10900-sdm660.0
- Merge Sony 47.1.A.16.20 Kernel
- Merge Linux 4.4.156 kernel

Conflicts due to Sony-specific changes:

- drivers/media/platform/msm/camera_v2/pproc/cpp/msm_cpp.c (LA.UM.6.2.r1-10900-sdm660.0)
- drivers/pwm/pwm-qpnp.c (LA.UM.6.2.r1-10900-sdm660.0)
- drivers/video/fbdev/msm/mdss_compat_utils.c (LA.UM.6.2.r1-10900-sdm660.0)
- include/uapi/media/msm_camsensor_sdk.h (LA.UM.6.2.r1-10900-sdm660.0)
- include/uapi/media/msmb_camera.h (LA.UM.6.2.r1-10900-sdm660.0)
- drivers/staging/android/ion/ion_priv.h (4.4.156)
- kernel/fork.c (4.4.156)

All resolved fine.

### CODE REVIEW

**Comment by derfelot** [comment]
Making a test build now.

**Comment by derfelot** [comment]
Should be good to go.

**Comment by derfelot** [comment]
Merged Sony 47.1.A.16.20 kernel as well. All good.

**Comment by derfelot** [comment]
Merged Linux 4.4.156 kernel as well. All good.

Minor revision is now 2x that of stock (78 vs 156) 🎉   :)

**Comment by derfelot** [comment]
Thanks, I'll have a look.

I thought the LA.UM.6.2.r1-10900-sdm660.0 and LA.UM.6.4.r1-10900-8x98.0 branches were identical.

**Comment by ShevT** [comment]
Alas, this is not so :)

**Comment by derfelot** [comment]
I had a quick check, please be aware that with your merge, you are reverting some previous commits, such as:

https://github.com/cryptomilk/android_kernel_sony_msm8998/commit/97cb6585430fab7617ab60f5e85227729ad151bf#diff-047bb9f1606259aac5bf22c23363f84b
https://github.com/cryptomilk/android_kernel_sony_msm8998/commit/041017d922a1d5de4502a35c67c8dc62d5f98262#diff-047bb9f1606259aac5bf22c23363f84b
https://github.com/cryptomilk/android_kernel_sony_msm8998/commit/1c88d4df9fb2cabaa209ac1e22780e22b1eb9731#diff-047bb9f1606259aac5bf22c23363f84b
https://github.com/cryptomilk/android_kernel_sony_msm8998/commit/8a9d69d704ca5237ba9a4dcdc926759b0cb78241#diff-047bb9f1606259aac5bf22c23363f84b

Some of which were required to build without LFR3 enabled.

I will test the remaining stuff soon. Thanks again. :)

**Pull request merged**
